server.address=0.0.0.0
server.port=8080

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS REAL (H2)
# ==========================================
spring.application.name=restaurante-pos

# Conexión local segura
spring.datasource.url=jdbc:h2:mem:restaurantedb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sanjuanera123

# Mapeo Automático de Tablas SQL desde Java
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola Web de Administración (localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# CORREGIDO: Propiedad bien escrita y en una sola línea
spring.h2.console.settings.trace=false
